const styles = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 57px)",
    width: "100%",
    boxSizing: "border-box",
    padding: "0px 16px 16px",
    background: "#0a0a0a",
    color: "#e8e8e8",
    fontFamily: "'DM Sans', sans-serif",
  },
  centered: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    gap: "12px",
    width: "100%",
  },
  heading: {
    fontSize: "34px",
    fontWeight: "700",
    color: "#e8e8e8",
    fontFamily: "'DM Sans', sans-serif",
    margin: 0,
  },
  subheading: {
    fontSize: "17px",
    color: "#555",
    fontFamily: "'DM Sans', sans-serif",
    margin: "0 0 16px 0",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingBottom: "16px",
    maxWidth: "720px",
    width: "100%",
    alignSelf: "center",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
  },
  bubble: {
    maxWidth: "80%",
    padding: "10px 16px",
    borderRadius: "10px",
    border: "1px solid #262626",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  roleLabel: {
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: "#555",
  },
  bubbleText: {
    fontSize: "14px",
    lineHeight: "1.6",
    margin: 0,
    whiteSpace: "pre-wrap",
  },

  // input
  inputWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    maxWidth: "720px",
    width: "100%",
    alignSelf: "center",
    
  },
  inputBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#141414",
    border: "1px solid #262626",
    borderRadius: "12px",
    padding: "10px 12px",
  },
  iconBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: "20px",
    cursor: "pointer",
    lineHeight: 1,
    padding: "0 4px",
    display: "flex",
    alignItems: "center",
  },
  textarea: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "#e8e8e8",
    fontSize: "14px",
    resize: "none",
    fontFamily: "'Syne', sans-serif",
    lineHeight: "1.5",
  },
  sendBtn: {
    background: "#1e1e1e",
    border: "1px solid #333",
    color: "#e8e8e8",
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // paper filter dropdown
  dropdown: {
    position: "absolute",
    bottom: "40px",
    left: "0",
    background: "#1c1c1c",
    border: "1px solid #2a2a2a",
    borderRadius: "10px",
    padding: "6px",
    minWidth: "260px",
    maxHeight: "220px",
    overflowY: "auto",
    zIndex: 100,
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
  },
  dropdownBtn: {
    display: "block",
    width: "100%",
    background: "transparent",
    border: "none",
    borderRadius: "7px",
    padding: "8px 12px",
    fontSize: "13px",
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "'Syne', sans-serif",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  dropdownItem: {
    padding: "8px 12px",
    fontSize: "13px",
    color: "#555",
    margin: 0,
  },

  // selected paper tag shown above input
  paperTag: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "rgba(0,196,160,0.08)",
    border: "1px solid rgba(0,196,160,0.2)",
    borderRadius: "8px",
    padding: "6px 12px",
    alignSelf: "flex-start",
  },
  paperTagText: {
    fontSize: "12px",
    color: "#00c4a0",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "400px",
  },
  clearBtn: {
    background: "none",
    border: "none",
    color: "#00c4a0",
    cursor: "pointer",
    fontSize: "12px",
    padding: "0",
    lineHeight: 1,
  },

  sourcesBox: {
  marginTop: "10px",
  paddingTop: "10px",
  borderTop: "1px solid #262626",
  display: "flex",
  flexDirection: "column",
  gap: "6px",
  },
  sourcesLabel: {
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: "#555",
  },
  sourceRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
  },
  sourceFile: {
    fontSize: "12px",
    color: "#888",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  sourceChunk: {
    fontSize: "11px",
    color: "#555",
    flexShrink: 0,
    background: "#1e1e1e",
    border: "1px solid #2a2a2a",
    borderRadius: "4px",
    padding: "2px 6px",
  },
};

export default styles;